name: Build sing-box image

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '10 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: sing-box
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: SagerNet
          repo: sing-box
          excludes: prerelease, draft
      - name: Check image
        id: image_exists
        continue-on-error: true
        uses: cloudposse/github-action-docker-image-exists@0.1.2
        with:
          registry: registry.hub.docker.com
          organization: "itdoginfo"
          repository: "sing-box"
          tag: ${{ steps.sing-box.outputs.release }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ steps.image_exists.conclusion != 'success' }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.image_exists.conclusion == 'failure'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: steps.image_exists.conclusion == 'failure'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        if: steps.image_exists.conclusion == 'failure'
        with:
          push: true
          build-args: RELEASE=${{ steps.sing-box.outputs.release }}
          tags: itdoginfo/sing-box:${{ steps.sing-box.outputs.release }}
          platforms: linux/386,linux/amd64,linux/arm64,linux/s390x